### ISSUE TITLE
Vite 4.x compatibility

### ISSUE THREAD

**Issue by tonai** [antfu/vite-plugin-vue-server-ref#2]
### Clear and concise description of the problem

In `package.json` peerDependencies states that `vite` should be 2.x or 3.x.
It would be greate if it can be compatible with `vite` 4.x.

### Suggested solution

Maybe there is nothing to do but to update `package.json`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
PR welcome if you want :)

**Comment by so1ve** [comment]
I guess it's supported now
